# -*- coding: utf-8 -*-
"""TsuGradApp.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y4zNVjOh7AYcCp4BqmqggehiV2HL__if
"""

import matplotlib.pyplot as plt

import streamlit as st
import pandas as pd
import plotly.graph_objects as go
from sklearn.linear_model import LogisticRegression
import matplotlib.pyplot as plt

# Student profiles for simulation
students_data = {
    "John Doe": {"GPA": 2.51, "Hours": 33, "Attendance": 48, "Semester": "Spring"},
    "Jane Smith": {"GPA": 3.2, "Hours": 62, "Attendance": 92, "Semester": "Fall"},
    "Aliyah Green": {"GPA": 1.9, "Hours": 27, "Attendance": 50, "Semester": "Summer"},
    "Carlos Rivera": {"GPA": 2.7, "Hours": 45, "Attendance": 72, "Semester": "Fall"},
    "Brian West": {"GPA": 2.0, "Hours": 45, "Attendance": 36, "Semester": "Summer"},
    "Hannah Lee": {"GPA": 3.9, "Hours": 90, "Attendance": 98, "Semester": "Spring"},
    "Samir Khan": {"GPA": 2.3, "Hours": 60, "Attendance": 60, "Semester": "Spring"},
    "Ava Brooks": {"GPA": 2.8, "Hours": 75, "Attendance": 85, "Semester": "Fall"},
    "Marcus King": {"GPA": 2.5, "Hours": 50, "Attendance": 65, "Semester": "Summer"},
    "Emily Clark": {"GPA": 3.6, "Hours": 100, "Attendance": 99, "Semester": "Fall"}
}

# Sidebar Inputs
st.sidebar.header("Select Student")
selected_name = st.sidebar.selectbox("", list(students_data.keys()))
student = students_data[selected_name]

st.sidebar.markdown("### Enter Student Info")
gpa = st.sidebar.slider("GPA", 0.0, 4.0, student["GPA"], 0.01)
hours = st.sidebar.number_input("Credit Hours Completed", 0, 150, student["Hours"])
attendance = st.sidebar.slider("Attendance Rate (%)", 0, 100, student["Attendance"])
semester = st.sidebar.selectbox("Current Semester", ["Fall", "Spring", "Summer"], index=["Fall", "Spring", "Summer"].index(student["Semester"]))

# Title
st.title("\U0001F393 TSU AI Graduation Success Companion")

# Risk Prediction Section
st.subheader("\U0001F4AB Risk Prediction")
st.button("Predict Academic Risk")

# Risk Logic
risk = "High" if gpa < 2.5 or attendance < 70 else "Medium" if gpa < 3.0 else "Low"
st.success(f"Predicted Risk Level: {risk}")

# Risk Explanation (10 sentence textflow)
st.markdown("""
A student's predicted academic risk is calculated based on GPA, attendance, and credit progression.
GPA below 2.5 triggers high-risk categorization due to potential academic probation.
Attendance lower than 70% correlates with reduced class performance and disengagement.
Credit hour accumulation helps assess time-to-degree and momentum.
High-risk students may face barriers like academic burnout, life stressors, or unclear goals.
The model weighs historical patterns and aligns thresholds with graduation benchmarks.
GPA volatility over time may also indicate unstable academic standing.
Low attendance can signal logistical issues or lack of motivation.
The AI model continuously adjusts predictions with new inputs.
Early identification allows for timely advising, targeted support, and retention efforts.
""")

# ML-Based Risk Prediction
st.subheader("\U0001F916 ML-Based Logistic Regression Risk Score")
training_data = pd.DataFrame({
    'GPA': [2.0, 2.3, 3.0, 3.5, 1.8, 2.7, 2.5, 2.1, 3.2, 2.9],
    'Attendance': [55, 60, 85, 95, 45, 70, 80, 58, 90, 88],
    'Credit_Hours': [30, 40, 60, 90, 25, 50, 70, 35, 80, 65],
    'Risk_Label': [1, 1, 0, 0, 1, 0, 0, 1, 0, 0]
})
X = training_data[['GPA', 'Attendance', 'Credit_Hours']]
y = training_data['Risk_Label']
ml_model = LogisticRegression()
ml_model.fit(X, y)
new_input = pd.DataFrame([{'GPA': gpa, 'Attendance': attendance, 'Credit_Hours': hours}])
prob = ml_model.predict_proba(new_input)[0][1]
predicted_label = ml_model.predict(new_input)[0]
pred_text = "High" if predicted_label == 1 else "Low"
st.info(f"ML Predicted Risk: {pred_text} ({prob*100:.2f}%)")

# Personalized Combined Path
st.markdown("""
Based on both the rule-based and ML risk scores, this student may require multi-layered support.
Weekly academic coaching, tutoring referrals, and GPA recovery benchmarks should be considered.
Proactive communication and advisor outreach are recommended.
The advising plan should incorporate SMART goals tied to class performance and credit hour recovery.
Flexible scheduling options may enhance attendance and reduce overload.
Motivational strategies and goal-tracking tools can reinforce progress.
Integrated feedback loops between faculty and advising ensure real-time monitoring.
Any early gains should be reinforced to build momentum.
Students at this profile should also receive policy navigation assistance.
Engagement and belief in the plan are critical to long-term academic recovery.
""")

# Personalized Advising Plan
st.subheader("\U0001F9D1‍\U0001F4DA Personalized Advising Plan")
st.info(f"""
Based on your inputs (GPA {gpa}, attendance {attendance}%), your advising plan includes targeted support.
Engage in structured academic workshops, time management training, and one-on-one peer mentorship.
Continued advisor meetings will be required, and you are encouraged to use the Student Success Center.
Flexible course scheduling and summer courses may be discussed.
Recovery milestones and weekly check-ins will track your progress.
Plan adjustments will be based on academic recovery markers.
Your path to graduation is possible with consistent effort and full engagement.
Faculty engagement will support personalized interventions.
Advisors may recommend bridge programs, tutoring, or course repetitions.
Progress should be monitored through GPA dashboards and feedback loops.
""")

# Outreach Message
st.subheader("\U0001F4E2 Outreach Message")
st.markdown("**Generated Message**")
st.text_area("", f"Hi {selected_name}, we noticed your GPA is {gpa}. Your success matters — let's build a tailored support plan this semester. Please meet with your advisor and take advantage of academic coaching and summer bridge opportunities.", height=100)

# TSU Policy Advisor
st.subheader("\U0001F4C8 TSU Policy Advisor")
policy = st.selectbox("Ask About:", ["maymester_tuition", "credit_limit", "housing_support"])
if policy == "maymester_tuition":
    msg = "Students with 2.5+ GPA by Fall and advisor approval may qualify for MayMester waiver."
elif policy == "credit_limit":
    msg = "Students above 90 hours may require override for additional courses."
else:
    msg = "Eligible students can access TSU housing support under special programs."
st.write(msg)

# Policy Advisor Insight (10 sentences)
st.markdown("""
TSU academic policies are designed to support progression and graduation. Credit limits are enforced to manage academic workload. GPA thresholds influence eligibility for financial aid, summer enrollment, and course load exceptions. Understanding policies helps students navigate exceptions with advisor support. Policy advisement ensures students remain on track within institutional compliance. For example, Maymester tuition waivers can reduce financial strain while keeping students on schedule. Housing support provides additional structure for at-risk students. Advisors guide appeals or overrides aligned with student goals. Clear policy communication reduces drop-off due to misunderstanding. Policy insights help tailor student recovery plans effectively.
""")

# Title and Setup
st.title("📊 GPA Snapshot")
st.markdown("### Linear GPA Visualization")

# Sample GPA data per semester for the selected student
gpa_data = {
    "Semester": ["Spring", "Summer", "Fall"],
    "GPA": [gpa - 0.2, gpa, gpa + 0.1]
}

df = pd.DataFrame(gpa_data)

# Linear Chart
fig, ax = plt.subplots()
ax.plot(df["Semester"], df["GPA"], marker='o', linestyle='-', color='skyblue')
ax.set_title("GPA Over Semesters")
ax.set_xlabel("Semester")
ax.set_ylabel("GPA")
ax.set_ylim(0, 4)
ax.grid(True)

# Show plot in Streamlit
st.pyplot(fig)